### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by throwawayslee** [joshjdevl/libsodium-jni#54]
Hi, Thanks for working on this and making it available to everyone. I have noticed that there are not very many comments in the code. It would be incredibly useful to new users to this lib such as myself in helping understand how everything is working. If you have the time to add some in, it would be much appreciated.

**Comment by throwawayslee** [comment]
Ok, after looking around a bit more it does look like some classes are well commented. I am still not sure how I am supposed to provide a key to a new SecretBox though. do I just write in a "string litteral" . tobytes() ?

**Comment by kalaspuffar** [comment]
Hi @throwawayslee 

A good way to figure out how things should be used is to check the test using the feature, if available.

In this case, you can look at
https://github.com/joshjdevl/libsodium-jni/blob/master/src/test/java/org/libsodium/jni/crypto/SecretBoxTest.java

This test case shows you a couple of invalid use cases, one of them is entering any strings bytes into the constructor which should lead to an exception. Usually, keys represented as fixed length byte arrays. In this case, a key with the format below could be used. This key value is in hex and needs to be decoded before use but there is an overloaded constructor to do this. So you have multiple choices to supply a key. Hope this helps otherwise please clarify and I'll try to help.

public static final String SECRET_KEY = "1b27556473e985d462cd51197a9a46c76009549eac6474f206c4ee0844f68389";

Best regards
Daniel
