### ISSUE TITLE
sodium_version_string()  crashes JVM

### ISSUE THREAD

**Issue by ppmag** [joshjdevl/libsodium-jni#55]
To reproduce:

```
     try {
            Method method1 = Class.forName("org.libsodium.jni.SodiumJNI").getMethod("sodium_init");
            int res = (int)method1.invoke(null);

            Method method = Class.forName("org.libsodium.jni.SodiumJNI").getMethod("sodium_version_string");
            method.invoke(null);

        } catch (Exception ex) {}
```

Crashes on last call with:

`A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: attempt to return an instance of java.lang.String from byte[] org.libsodium.jni.SodiumJNI.sodium_version_string()`

**Comment by kalaspuffar** [comment]
Hi @ppmag 

I'm not sure if the API has changed since last year but today you're required to run ```NaCl.sodium();``` before any calls to SodiumJNI. 

Furthermore, the sodium_version_string returns a byte array so maybe your code later in execution makes some assumption that the return value should be a string?

Best regards
Daniel
