### ISSUE TITLE
Question on aar and allowbackup

### ISSUE THREAD

**Issue by bufke** [joshjdevl/libsodium-jni#76]
When I install the aar I get 

```
Manifest merger failed : Attribute application@allowBackup value=(true) from AndroidManifest.xml:23:3-29
        is also present at [com.github.joshjdevl.libsodiumjni:libsodium-jni-aar:1.0.7-SNAPSHOT] AndroidManifest.xml:11:18-45 value=(false).
```

That's easy enough to resolve. But why does this happen? Does something about libsodium-jni break allowBackup? I assume it's coming from https://github.com/joshjdevl/libsodium-jni/blob/master/src/main/AndroidManifest.xml#L2

**Comment by joshjdevl** [comment]
This was done so that [sensitive information](https://developer.android.com/guide/topics/data/autobackup.html#EnablingAutoBackup) such as keys are not backed up.

> You may want to disable backups when your app can recreate its state through some other mechanism or when your app deals with sensitive information that should not be backed up.

**Comment by bufke** [comment]
Makes sense to be default then. Cool.

**Comment by joshjdevl** [comment]
If there is a way an application can override the defaults, please feel free to make a notation.

**Comment by bufke** [comment]
You can add this attribute to the application tag the AndroidManifest.xml to override it. `tools:replace="android:allowBackup"`

**Comment by ybbarng** [comment]
@joshjdevl 
https://developer.android.com/guide/topics/data/autobackup
The backup affects only files and I don't agree with that there is any file that relates to the secret keys.
Is there any file that has the secret keys?
If not, it seems that there is no reason set it to false by this library.
I think the value has to be managed by the application developer who creates the databases.

**Comment by joshjdevl** [comment]
> I think the value has to be managed by the application developer who creates the databases.

Libsodium enables the application developer to manage the allowBackup value. The application developer is able to override the allowBackup value by specifying 
`tools:replace="android:allowBackup"`

**Comment by ybbarng** [comment]
I'm not saying that there is no way to set that value to true, but this library is doing overactive.
My company supplies android library to many partners, and because of the need of encryption, we adopt this awesome library.
However, because of the set value of allowBackup, we need to say to all of the partners that you need to modify it with replace - aar does not support [fatty-build](https://github.com/Vigi0303/fat-aar-plugin) officially -.
I think it is not a good situation, and the problem is in here. it is the reason why I commented.
There are two options, one is that if you understand, then this library is modified, and we use yours with gratitude, the other is that fork this repo and modify the attribute and re-build to use.
I think the first one is better approach, so please review it.
