### ISSUE TITLE
crypto_secretbox_keygen is not found

### ISSUE THREAD

**Issue by r3za13** [joshjdevl/libsodium-jni#96]
I want to use this method : crypto_secretbox_keygen, for generating secret key for using in crypto_secretbox_easy method but it is not found in this library.could you provide this method or any alternative method for generating secret box key?

**Comment by kalaspuffar** [comment]
Hi @r3za13 

The ```crypto_secretbox_keygen``` is not available but when I looked into the code for libsodium I noticed it just uses ```randombytes_buf``` with a length of 32 bytes in order to create a key.

In Java, we have many functions to create random bytes. For instance, you could do

```
byte[] key = new byte[32];
byte[] nonce = new byte[24];
SecureRandom sr = SecureRandom.getInstanceStrong();
sr.nextBytes(key);
sr.nextBytes(nonce);
```

This function uses the same or equal sources of random as libsodium.

Quote from the documentation:
```
The library provides a set of functions to generate unpredictable data, suitable for creating secret keys.
On Windows systems, the RtlGenRandom() function is used
On OpenBSD and Bitrig, the arc4random() function is used
On recent Linux kernels, the getrandom system call is used
On other Unices, the /dev/urandom device is used
If none of these options can safely be used, custom implementations can easily be hooked.
```

Best regards
Daniel

**Comment by joshjdevl** [comment]
closing until further comments or details.
